#!/bin/bash
t=$1
pc=$2
rm -rf staticb.dat
	for j in 32 50 500 512 1000 1024 2000 2048 
        do
                if [ $t -lt $j ]
                then
			echo $j $t
			cut -d' ' -f$pc $j.$t >> option2.$t.dat
		fi
	done


#for i in 1 2 3 4 5 6 7 8 9 10 11 
#do
        #echo "$user " >> totalcycles
        #sed -e 's/$/`echo "$user "`/g' < $FILENAME > totalcycles
        #awk ' { print $1"\{ echo $user \} " } '  < $FILENAME > totalcyclesi

 #       cut -d' ' -f$pc $p.$i >> option2.$p.dat

#done

